Add custom protocol
lifeomic/twilio-webhook-validator-koa pull request #15
Opened 2019-12-11 12:46 UTC by Igor-lkm

We are able to set custom host `webhookValidator({ host })`. 

It make sense also to have an option to set a protocol. E.g. when endpoint is behind a proxy (TLS termination proxy).

Example:
```
webhookValidator({
  host: ctx.header['x-forwarded-host'],
  protocol: ctx.header['x-forwarded-proto']
});
``` 

This PR would add an optional protocol.

2019-12-11 20:27 UTC, 0xch4z requested changes
Thanks! This looks great, I just had one piece of stylistic feedback.

2019-12-11 20:27 UTC, Charliekenney23 commented on test/webhookValidator.test.ts
> +  const protocol = options ? options.protocol || 'http' : 'http';
I'd prefer

```typescript
const protocol = options && options.protocol || 'http';
```

2019-12-11 20:27 UTC, Charliekenney23 commented on README.md
> +# Example usage with custom host and port (e.g. behind proxy)
Thanks for updating the docs 😄

2019-12-12 09:04 UTC, Igor-lkm commented on test/webhookValidator.test.ts
> +  const protocol = options ? options.protocol || 'http' : 'http';
Don!

2019-12-12 13:34 UTC, 0xch4z approved these changes

2019-12-12 13:35 UTC, merged

2019-12-12 13:39 UTC, Charliekenney23 commented
@Igor-lkm This has been released as part of 1.2.0.